# Error messages
ERROR_FILE_NOT_FOUND_IN_REQUEST = "'file' not found in request body"
ERROR_INVALID_FILE = "Invalid file"
ERROR_EVENT_LOG_ID_NOT_FOUND_IN_REQUEST = "'event_log_id' not found \
  in request body"
ERROR_EVENT_LOG_DOESNT_EXIST = "Event log doesn't exist"

# Messages
MESSAGE_EVENT_LOG_UPLOAD_SUCCESS = "Event log uploaded successfully"

# File extension constants
XES_EXTENSION = "xes"
CSV_EXTENSION = "csv"
ALLOWED_EXTENSIONS = {XES_EXTENSION, CSV_EXTENSION}

# dictionary keys
DICT_KEY_OBJECTS_CONSTANT = "objects"
DICT_KEY_EDGES_CONSTANT = "edges"
DICT_KEY_LAYOUT_INFO_PETRI = "LAYOUT_INFORMATION_PETRI"
DICT_KEY_LAYOUT_X = "x"
DICT_KEY_LAYOUT_Y = "y"
DICT_KEY_LAYOUT_HEIGHT = "height"
DICT_KEY_LAYOUT_WIDTH = "width"
DICT_KEY_PERF_INFO_PETRI = "PERFORMANCE_INFORMATION_PETRI"
DICT_KEY_PERF_MEAN = "mean"
DICT_KEY_PERF_STDEV = "stdev"
DICT_KEY_FREQUENCY = "successor_frequencies"

# default performance values
PERF_MEAN_DEFAULT_VALUE = 0.0
PERF_STDEV_DEFAULT_VALUE = 0.0

# declaration constants
DECLARATION_COLOR_REQUEST = "REQUEST"
DECLARATION_COLOR_REQUEST_DATATYPE = "int"
DECLARATION_COLOR_REQUEST_VARIABLE = "r"
DECLARATION_COLOR_REQUEST_ITER_INDEX_START = 1
DECLARATION_COLOR_REQUEST_ITER_INDEX_END = 5
DECLARATION_COLOR_REQUEST_ITER_INSTANCE = "rq"
DECLARATION_COLOR_REQUEST_INSTANCES = DECLARATION_COLOR_REQUEST + ".all()"

# orientation constants
PLACE_TO_TRANS_ORIENTATION = "PtoT"
TRANS_TO_PLACE_ORIENTATION = "TtoP"
