name: CI Pipeline
on:
  push:
    branches:
      - unittest-coverage
  pull_request:
    branches:
      - unittest-coverage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"    
      - name: Install or upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install graphviz
        run: sudo apt-get install graphviz 
      - name: Install dependencies
        run: make init
      - name: Run tests with coverage/unittest
        run: make test 