name: CI Pipeline
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"    
      - name: Install or upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install graphviz
        run: sudo make linux-graphviz
      - name: Install dependencies
        run: make init
      - name: Run tests with coverage/unittest
        run: make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: aecea6cf-8e41-42ee-9433-016a12208552 # upload token needs to be stored in secrets
          fail_ci_if_error: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Login to Heroku Container registry
        env: 
          HEROKU_API_KEY: 8e0c1634-5e2e-46d6-940a-6b3bd198b467 # this is a test account, api key needs to be stored in secrets
        run: heroku container:login
      - name: Build and push to Heroku
        env:
          HEROKU_API_KEY: 8e0c1634-5e2e-46d6-940a-6b3bd198b467
        run: heroku container:push -a cpn-model-process-discovery-1 web # app name needs to be stored in secrets
      - name: Release to Heroku
        env:
          HEROKU_API_KEY: 8e0c1634-5e2e-46d6-940a-6b3bd198b467
        run: heroku container:release -a cpn-model-process-discovery-1 web # app name needs to be stored in secrets